---
deployment:
  tasks:
    - export DEPLOYPATH=/home/natalia4/public_html
    - /bin/cp -R develop $DEPLOYPATH
    - /bin/cp -R locales $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp asset-manifest.json $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp logo192.png $DEPLOYPATH
    - /bin/cp logo512.png.json $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp logo.svg $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH
    - /bin/cp rodots.txt $DEPLOYPATH
